<?xml version="1.0" encoding="UTF-8"?>
<!--DTD validation-->
<!DOCTYPE listing [
<!ELEMENT listing (movie*)>
<!ELEMENT movie (mtitle,genre,cast,location,price)>
<!ELEMENT mtitle (#PCDATA)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT cast (#PCDATA)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT image (#PCDATA)>
<!ELEMENT video (#PCDATA)>
<!ATTLIST movie id CDATA #REQUIRED>
]>
<listing>
    <movie id="1">
        <mtitle>A nightmare on Elm Street</mtitle>
        <genre>empty</genre>
        <cast>empty</cast>
        <location>Cinema1</location>
        <price>1€</price>
        <description>
            Teenager Nancy Thompson must uncover the dark truth concealed by her parents after she and her friends become targets of the spirit of a serial killer with a bladed glove in their dreams, in which if they die, it kills them in real life.
        </description>
        <image>empty</image>
        <video>empty</video>
    </movie>
    <movie id="2">
        <mtitle>Jurassic Park</mtitle>
        <genre>empty</genre>
        <cast>empty</cast>
        <location>Cinema2</location>
        <price>2€</price>
        <description>
            The Mummy is a rousing, suspenseful and horrifying epic about an expedition of treasure-seeking explorers in the Sahara Desert in 1925. Stumbling upon an ancient tomb, the hunters unwittingly set loose a 3,000-year-old legacy of terror, which is embodied in the vengeful reincarnation of an Egyptian priest who had been sentenced to an eternity as one of the living dead.
        </description>
        <image>https://i.imgur.com/JYQBHvb.jpeg</image>
        <video>https://www.youtube.com/embed/lc0UehYemQA</video>
    </movie>
    <movie id="3">
        <mtitle>The Mummy</mtitle>
        <genre>empty</genre>
        <cast>empty</cast>
        <location>Cinema3</location>
        <price>3€</price>
        <description>
            They are the best-kept secret in the universe. Working for a highly funded yet unofficial government agency, Kay (Tommy Lee Jones) and Jay (Will Smith) are the Men in Black, providers of immigration services and regulators of all things alien on Earth. While investigating a series of unregistered close encounters, the MIB agents uncover the deadly plot of an intergalactic terrorist who is on a mission to assassinate two ambassadors from opposing galaxies currently in residence in New York City.
        </description>
        <image>empty</image>
        <video>empty</video>
    </movie>
    <movie id="4">
        <mtitle>Men In Black</mtitle>
        <genre>empty</genre>
        <cast>empty</cast>
        <location>Cinema4</location>
        <price>4€</price>
        <description>
            Teenager Nancy Thompson must uncover the dark truth concealed by her parents after she and her friends become targets of the spirit of a serial killer with a bladed glove in their dreams, in which if they die, it kills them in real life.
        </description>
        <image>empty</image>
        <video>empty</video>
    </movie>
</listing>